name: Appsterdam Embassy Page
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "pages/page:num"
timezone: Europe/Amsterdam
exclude: [LICENCE, README.md]
permalink: pages/:title/
embassy:
  name: Appsterdam Brasil
  url: http://brasil.appsterdam.rs
  location: Sao Paulo
  email: brasil@appsterdam.rs
  social:
    twitter:
      handle: "@AppsterdamBR"
      url: http://www.twitter.com/appsterdamBR
    github:
      handle: AppsterdamBR
      url: https://www.github.com/appsterdamBR
    facebook: http://www.facebook.com/appsterdamBR
